# Generated by Django 3.2.8 on 2022-12-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.CharField(max_length=200, verbose_name='描述'),
        ),
    ]
