# Generated by Django 3.2.8 on 2022-12-24 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wxcloudrun', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
